### ISSUE TITLE
How can I run this repo?

### ISSUE THREAD

**Issue by yugaljain1999** [Alea4jacta6est/Chatbot-banking-area#1]
@Alea4jacta6est I am facing tensorflow==1.12 incompatibility with rasa-core,rasa-NLU. How can I fix that?
Can you specifiy which commands I should run to run this repo in python 3.7?
Please help me in this issue. It's very important.

Thanks

**Comment by Alea4jacta6est** [comment]
Hello, unfortunately this repository is not supported anymore and as the versions of Rasa were installed from git directly, I don't remember which one worked fine (you can find it out by dates of publication of my repo and releases of Rasa at that period of time). Also, the heart of the app is not open sourced, so, it's almost useless for you if you wanted some features for financial domain.

However, I would advise you to take a look at Rasa's blog with tutorials https://blog.rasa.com/ and their YouTube channel https://www.youtube.com/channel/UCJ0V6493mLvqdiVwOKWBODQ where you can find all up-to-date information and quite easily build your own chatbot.

**Comment by yugaljain1999** [comment]
@Alea4jacta6est Okay Thanks for info.
